using System;
using System.Collections.Generic;
using System.Linq;

namespace RestaurantManagement
{
    // Represents a menu item available in the restaurant.
    public class MenuItem
    {
        public int ItemId { get; set; }
        public string ItemName { get; set; }
        public string Category { get; set; }
        public decimal Price { get; set; }

        public MenuItem(
            int itemId,
            string itemName,
            string category,
            decimal price)
        {
            ItemId = itemId;
            ItemName = itemName;
            Category = category;
            Price = price;
        }

        // Displays menu item details.
        public void Display()
        {
            Console.WriteLine($"Item ID   : {ItemId}");
            Console.WriteLine($"Item Name : {ItemName}");
            Console.WriteLine($"Category  : {Category}");
            Console.WriteLine($"Price     : ₹{Price:F2}");
            Console.WriteLine("--------------------------------");
        }
    }


    // Represents a customer order containing multiple menu items.
    public class Order
    {
        public int OrderId { get; set; }
        public List<MenuItem> Items { get; set; }

        public Order(int orderId)
        {
            OrderId = orderId;
            Items = new List<MenuItem>();
        }

        // Adds a menu item to the order.
        public void AddItem(MenuItem item)
        {
            Items.Add(item);
        }

        // Calculates the total price of all items in the order.
        public decimal CalculateTotal()
        {
            return Items.Sum(item => item.Price);
        }

        // Displays order details.
        public void Display()
        {
            Console.WriteLine($"Order ID: {OrderId}");
            Console.WriteLine("Ordered Items:");

            foreach (MenuItem item in Items)
            {
                Console.WriteLine(
                    $"{item.ItemName} - ₹{item.Price:F2}");
            }

            Console.WriteLine(
                $"Total Amount: ₹{CalculateTotal():F2}");
        }
    }


    // Manages the restaurant menu and customer orders.
    public class Restaurant
    {
        private readonly List<MenuItem> menuItems;
        private readonly List<Order> orders;

        public Restaurant()
        {
            menuItems = new List<MenuItem>();
            orders = new List<Order>();
        }

        // Adds a new item to the restaurant menu.
        public void AddMenuItem(MenuItem item)
        {
            menuItems.Add(item);
        }

        // Returns all menu items.
        public List<MenuItem> GetAllMenuItems()
        {
            return menuItems;
        }

        // Returns menu items belonging to a specific category.
        public List<MenuItem> GetItemsByCategory(
            string category)
        {
            return menuItems
                .Where(item =>
                    item.Category.Equals(
                        category,
                        StringComparison.OrdinalIgnoreCase))
                .ToList();
        }

        // Creates and adds a new customer order.
        public void AddOrder(Order order)
        {
            orders.Add(order);
        }

        // Returns an order using its unique ID.
        public Order? GetOrderById(int orderId)
        {
            return orders.FirstOrDefault(
                order => order.OrderId == orderId);
        }

        // Calculates the total revenue generated by all orders.
        public decimal CalculateTotalRevenue()
        {
            return orders.Sum(
                order => order.CalculateTotal());
        }

        // Displays all available menu items.
        public void DisplayMenu()
        {
            Console.WriteLine(
                "========== RESTAURANT MENU ==========");

            foreach (MenuItem item in menuItems)
            {
                item.Display();
            }
        }

        // Displays all customer orders.
        public void DisplayAllOrders()
        {
            Console.WriteLine(
                "========== CUSTOMER ORDERS ==========");

            foreach (Order order in orders)
            {
                order.Display();
                Console.WriteLine();
            }
        }
    }


    // Application entry point.
    public class Program
    {
        public static void Main(string[] args)
        {
            // Create restaurant instance.
            Restaurant restaurant =
                new Restaurant();


            // ==========================================
            // ADD MENU ITEMS
            // ==========================================

            restaurant.AddMenuItem(
                new MenuItem(
                    1,
                    "Margherita Pizza",
                    "Main Course",
                    299.00m));

            restaurant.AddMenuItem(
                new MenuItem(
                    2,
                    "Veg Burger",
                    "Main Course",
                    149.00m));

            restaurant.AddMenuItem(
                new MenuItem(
                    3,
                    "French Fries",
                    "Starter",
                    99.00m));

            restaurant.AddMenuItem(
                new MenuItem(
                    4,
                    "Cold Coffee",
                    "Beverage",
                    120.00m));

            restaurant.AddMenuItem(
                new MenuItem(
                    5,
                    "Chocolate Brownie",
                    "Dessert",
                    180.00m));


            // ==========================================
            // DISPLAY RESTAURANT MENU
            // ==========================================

            restaurant.DisplayMenu();


            // ==========================================
            // CREATE FIRST ORDER
            // ==========================================

            Order order1 =
                new Order(1001);

            order1.AddItem(
                restaurant.GetAllMenuItems()
                    .First(item => item.ItemId == 1));

            order1.AddItem(
                restaurant.GetAllMenuItems()
                    .First(item => item.ItemId == 3));

            order1.AddItem(
                restaurant.GetAllMenuItems()
                    .First(item => item.ItemId == 4));


            // ==========================================
            // CREATE SECOND ORDER
            // ==========================================

            Order order2 =
                new Order(1002);

            order2.AddItem(
                restaurant.GetAllMenuItems()
                    .First(item => item.ItemId == 2));

            order2.AddItem(
                restaurant.GetAllMenuItems()
                    .First(item => item.ItemId == 5));


            // ==========================================
            // ADD ORDERS TO RESTAURANT
            // ==========================================

            restaurant.AddOrder(order1);
            restaurant.AddOrder(order2);


            // ==========================================
            // DISPLAY ALL ORDERS
            // ==========================================

            Console.WriteLine();

            restaurant.DisplayAllOrders();


            // ==========================================
            // SEARCH ITEMS BY CATEGORY
            // ==========================================

            string category = "Main Course";

            Console.WriteLine(
                "========== ITEMS BY CATEGORY ==========");

            Console.WriteLine(
                $"Category: {category}");

            List<MenuItem> categoryItems =
                restaurant.GetItemsByCategory(category);

            foreach (MenuItem item in categoryItems)
            {
                item.Display();
            }


            // ==========================================
            // FIND ORDER BY ORDER ID
            // ==========================================

            int searchOrderId = 1001;

            Order? searchedOrder =
                restaurant.GetOrderById(searchOrderId);

            Console.WriteLine(
                "========== SEARCH ORDER ==========");

            if (searchedOrder != null)
            {
                searchedOrder.Display();
            }
            else
            {
                Console.WriteLine(
                    "Order not found.");
            }


            // ==========================================
            // DISPLAY TOTAL REVENUE
            // ==========================================

            Console.WriteLine();

            Console.WriteLine(
                "========== RESTAURANT REVENUE ==========");

            Console.WriteLine(
                $"Total Revenue: ₹{restaurant.CalculateTotalRevenue():F2}");
        }
    }
}